#' Run nlmixr2 model fitting in an isolated R subprocess
#'
#' This function runs a pharmacometric model defined by `f` and `dat` in a separate R process.
#' It supports user-defined `saem.control` and `table.control`, and safely captures fitting errors.
#'
#' @param modi Integer. The model number used to uniquely name temp files.
#' @param dat Data frame. Dataset used for model fitting.
#' @param f nlmixr model function. Generated by e.g. `ppkmodGen(..., return.func = TRUE)`.
#' @param saem.control A `saemControl()` object with user-defined fitting controls.
#' @param table.control A `tableControl()` object for table output configuration.
#'
#' @return A list with two elements:
#'   - `fit.s`: the fitted nlmixr2 object (or NULL if failed)
#'   - `loadError`: logical indicating if an error occurred
#'
#' @export
run_model_in_subprocess <- function(modi,
                                    dat,
                                    f,
                                    max_errors = 100,
                                    saem.control = NULL,
                                    table.control = NULL) {
  # Required package
  if (!requireNamespace("processx", quietly = TRUE)) {
    stop(
      "The 'processx' package is required. Please install it via install.packages('processx')."
    )
  }

  # Define temporary filenames
  temp_model_data <- paste0("temp_model_data_", modi, ".rds")
  temp_fit_result <- paste0("temp_fit_result_", modi, ".rds")
  temp_script <- paste0("temp_script_", modi, ".R")

  # Save model components to RDS
  saveRDS(
    list(
      f = f,
      dat = dat,
      saem.control = saem.control,
      table.control = table.control
    ),
    file = temp_model_data
  )

  # Create temporary R script for subprocess
  script_content <- sprintf(
    '
  suppressMessages({
    library(nlmixr2)
    library(rxode2)
  })

  model_data <- readRDS("%s")
  f <- model_data$f
  dat <- model_data$dat
  saem.control <- model_data$saem.control
  table.control <- model_data$table.control

  fit_result <- tryCatch({
    nlmixr2(
      f,
      dat,
      est = "saem",
      control = saem.control,
      table = table.control
    )
  }, error = function(e) {
    message("Model fitting error: ", e$message)
    NULL
  })

  saveRDS(fit_result, "%s")
  ',
    temp_model_data,
    temp_fit_result
  )

  # Write to script file
  writeLines(script_content, temp_script)

  # Launch subprocess
  p <-
    processx::process$new("Rscript",
                          c(temp_script),
                          stdout = "|",
                          stderr = "|")

  # Real-time monitoring
  error_count <- 0
  loadError <- FALSE

  while (p$is_alive()) {
    lines_out <- p$read_output_lines()
    lines_err <- p$read_error_lines()

    for (line in c(lines_out, lines_err)) {
      if (grepl("Model fitting error", line)) {
        error_count <- error_count + 1
        cat(sprintf(
          "Model %d: Error detected %d/%d\n",
          modi,
          error_count,
          max_errors
        ))
        if (error_count >= max_errors) {
          p$kill()
          cat(sprintf(
            "Model %d: Error count exceeded threshold. Terminated.\n",
            modi
          ))
          loadError <- TRUE
          break
        }
      }
    }

    Sys.sleep(0.1)
  }

  # Load results
  if (file.exists(temp_fit_result)) {
    fit.s <- readRDS(temp_fit_result)
  } else {
    fit.s <- NULL
    loadError <- TRUE
  }

  # Clean up
  unlink(c(temp_model_data, temp_fit_result, temp_script))

  return(list(fit.s = fit.s, loadError = loadError))
}
